# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_auto_20171109_0158'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userexercise',
            unique_together=set([]),
        ),
    ]
